import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row w-screen min-h-screen bg-white text-primary">
          <div className="flex flex-col flex-1">
            <main className="flex-1 overflow-auto h-full">
              <Header />
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
