import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { ToolkitProvider } from "@/components/ToolkitProvider";
import { Sidebar } from "@/components/Sidebar";
import { Body } from "@/components/Body";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ToolkitProvider>
        <Body>
          <Sidebar />
          <Header />
          {children}
        </Body>
      </ToolkitProvider>
    </html>
  );
}
